/**
 * Deterministic icon picker for agent avatars. Lead always gets a crown so
 * the coordinator visually pops. Workers get one of 30 distinct lucide
 * icons seeded by agent id (NOT name — names can change, ids don't).
 */

import {
  AArrowDown,
  AArrowUp,
  Accessibility,
  Activity,
  ActivitySquare,
  Airplay,
  AirVent,
  ALargeSmall,
  AlarmCheck,
  AlarmClock,
  AlarmClockCheck,
  AlarmClockMinus,
  AlarmClockOff,
  AlarmClockPlus,
  AlarmMinus,
  AlarmPlus,
  AlarmSmoke,
  Album,
  AlertCircle,
  AlertOctagon,
  AlertTriangle,
  AlignCenter,
  AlignCenterHorizontal,
  AlignCenterVertical,
  AlignEndHorizontal,
  AlignEndVertical,
  AlignHorizontalDistributeCenter,
  AlignHorizontalDistributeEnd,
  AlignHorizontalDistributeStart,
  AlignHorizontalJustifyCenter,
  AlignHorizontalJustifyEnd,
  AlignHorizontalJustifyStart,
  AlignHorizontalSpaceAround,
  AlignHorizontalSpaceBetween,
  AlignJustify,
  AlignLeft,
  AlignRight,
  AlignStartHorizontal,
  AlignStartVertical,
  AlignVerticalDistributeCenter,
  AlignVerticalDistributeEnd,
  AlignVerticalDistributeStart,
  AlignVerticalJustifyCenter,
  AlignVerticalJustifyEnd,
  AlignVerticalJustifyStart,
  AlignVerticalSpaceAround,
  AlignVerticalSpaceBetween,
  Ambulance,
  Ampersand,
  Ampersands,
  Amphora,
  Anchor,
  Angry,
  Annoyed,
  Antenna,
  Anvil,
  Aperture,
  Apple,
  AppWindow,
  AppWindowMac,
  Archive,
  ArchiveRestore,
  ArchiveX,
  AreaChart,
  Armchair,
  ArrowBigDown,
  ArrowBigDownDash,
  ArrowBigLeft,
  ArrowBigLeftDash,
  ArrowBigRight,
  ArrowBigRightDash,
  ArrowBigUp,
  ArrowBigUpDash,
  ArrowDown,
  ArrowDownAz,
  ArrowDownCircle,
  ArrowDownFromLine,
  ArrowDownLeft,
  ArrowDownLeftFromCircle,
  ArrowDownLeftFromSquare,
  ArrowDownLeftSquare,
  ArrowDownNarrowWide,
  ArrowDownRight,
  ArrowDownRightFromCircle,
  ArrowDownRightFromSquare,
  ArrowDownRightSquare,
  ArrowDownSquare,
  ArrowDownToDot,
  ArrowDownToLine,
  ArrowDownUp,
  ArrowDownWideNarrow,
  ArrowDownZa,
  ArrowLeft,
  ArrowLeftCircle,
  ArrowLeftFromLine,
  ArrowLeftRight,
  ArrowLeftSquare,
  ArrowLeftToLine,
  ArrowRight,
  ArrowRightCircle,
  ArrowRightFromLine,
  ArrowRightLeft,
  ArrowRightSquare,
  ArrowRightToLine,
  ArrowsUpFromLine,
  ArrowUp,
  ArrowUpAz,
  ArrowUpCircle,
  ArrowUpDown,
  ArrowUpFromDot,
  ArrowUpFromLine,
  ArrowUpLeft,
  ArrowUpLeftFromCircle,
  ArrowUpLeftFromSquare,
  ArrowUpLeftSquare,
  ArrowUpNarrowWide,
  ArrowUpRight,
  ArrowUpRightFromCircle,
  ArrowUpRightFromSquare,
  ArrowUpRightSquare,
  ArrowUpSquare,
  ArrowUpToLine,
  ArrowUpWideNarrow,
  ArrowUpZa,
  Asterisk,
  AsteriskSquare,
  Atom,
  AtSign,
  AudioLines,
  AudioWaveform,
  Award,
  Axe,
  Baby,
  Backpack,
  Badge,
  BadgeAlert,
  BadgeCent,
  BadgeCheck,
  BadgeDollarSign,
  BadgeEuro,
  BadgeHelp,
  BadgeIndianRupee,
  BadgeInfo,
  BadgeJapaneseYen,
  BadgeMinus,
  BadgePercent,
  BadgePlus,
  BadgePoundSterling,
  BadgeQuestionMark,
  BadgeRussianRuble,
  BadgeSwissFranc,
  BadgeTurkishLira,
  BadgeX,
  BaggageClaim,
  Balloon,
  Ban,
  Banana,
  Bandage,
  Banknote,
  BanknoteArrowDown,
  BanknoteArrowUp,
  BanknoteX,
  BarChart,
  BarChartBig,
  BarChartHorizontal,
  BarChartHorizontalBig,
  Barcode,
  Barrel,
  Baseline,
  Bath,
  Battery,
  BatteryCharging,
  BatteryFull,
  BatteryLow,
  BatteryMedium,
  BatteryPlus,
  BatteryWarning,
  Beaker,
  Bean,
  BeanOff,
  Bed,
  BedDouble,
  BedSingle,
  Beef,
  Beer,
  BeerOff,
  Bell,
  BellDot,
  BellElectric,
  BellMinus,
  BellOff,
  BellPlus,
  BellRing,
  BetweenHorizonalEnd,
  BetweenHorizonalStart,
  BetweenHorizontalEnd,
  BetweenHorizontalStart,
  BetweenVerticalEnd,
  BetweenVerticalStart,
  BicepsFlexed,
  Bike,
  Binary,
  Binoculars,
  Biohazard,
  Bird,
  Birdhouse,
  Bitcoin,
  Blend,
  Blinds,
  Blocks,
  Bluetooth,
  BluetoothConnected,
  BluetoothOff,
  BluetoothSearching,
  Bold,
  Bolt,
  Bomb,
  Bone,
  Book,
  BookA,
  BookAlert,
  BookAudio,
  BookCheck,
  BookCopy,
  BookDashed,
  BookDown,
  BookHeadphones,
  BookHeart,
  BookImage,
  BookKey,
  BookLock,
  BookMarked,
  BookMinus,
  Bookmark,
  BookmarkCheck,
  BookmarkMinus,
  BookmarkPlus,
  BookmarkX,
  BookOpen,
  BookOpenCheck,
  BookOpenText,
  BookPlus,
  BookSearch,
  BookTemplate,
  BookText,
  BookType,
  BookUp,
  BookUser,
  BookX,
  BoomBox,
  Bot,
  BotMessageSquare,
  BotOff,
  BottleWine,
  BowArrow,
  Box,
  Boxes,
  BoxSelect,
  Braces,
  Brackets,
  Brain,
  BrainCircuit,
  BrainCog,
  BrickWall,
  BrickWallFire,
  BrickWallShield,
  Briefcase,
  BriefcaseBusiness,
  BriefcaseConveyorBelt,
  BriefcaseMedical,
  BringToFront,
  Brush,
  BrushCleaning,
  Bubbles,
  Bug,
  BugOff,
  BugPlay,
  Building,
  Bus,
  BusFront,
  Cable,
  CableCar,
  Cake,
  CakeSlice,
  Calculator,
  Calendar,
  CalendarArrowDown,
  CalendarArrowUp,
  CalendarCheck,
  CalendarClock,
  CalendarCog,
  CalendarDays,
  CalendarFold,
  CalendarHeart,
  CalendarMinus,
  CalendarOff,
  CalendarPlus,
  CalendarRange,
  CalendarSearch,
  CalendarSync,
  Calendars,
  CalendarX,
  Camera,
  CameraOff,
  CandlestickChart,
  Candy,
  CandyCane,
  CandyOff,
  Cannabis,
  CannabisOff,
  Captions,
  CaptionsOff,
  Car,
  Caravan,
  CardSim,
  CarFront,
  Carrot,
  CarTaxiFront,
  CaseLower,
  CaseSensitive,
  CaseUpper,
  CassetteTape,
  Cast,
  Castle,
  Cat,
  Cctv,
  ChartArea,
  ChartBar,
  ChartBarBig,
  ChartBarDecreasing,
  ChartBarIncreasing,
  ChartBarStacked,
  ChartCandlestick,
  ChartColumn,
  ChartColumnBig,
  ChartColumnDecreasing,
  ChartColumnIncreasing,
  ChartColumnStacked,
  ChartGantt,
  ChartLine,
  ChartNetwork,
  ChartNoAxesColumn,
  ChartNoAxesColumnDecreasing,
  ChartNoAxesColumnIncreasing,
  ChartNoAxesCombined,
  Cherry,
  Cloud,
  Coffee,
  Compass,
  Crown,
  Diamond,
  Dog,
  Droplet,
  Feather,
  Fish,
  Flag,
  Flame,
  Flower2,
  Gem,
  Ghost,
  Gift,
  Globe,
  Heart,
  Key,
  Leaf,
  Lock,
  type LucideIcon,
  Map as MapIcon,
  Moon,
  Mountain,
  Music,
  Package,
  Palette,
  Pizza,
  Plane,
  Puzzle,
  Rabbit,
  Rocket,
  Shield,
  Skull,
  Snail,
  Snowflake,
  Sparkles,
  Sprout,
  Squirrel,
  Star,
  Sun,
  Sword,
  Target,
  Telescope,
  TreeDeciduous,
  Trophy,
  Turtle,
  Umbrella,
  Wand2,
  Zap,
} from "lucide-react";
import type { AgentAvatar } from "@/api/types";

/**
 * Compatibility-sensitive: do not reorder, add, or remove entries. Existing
 * agents rely on FNV-1a(agentId) % 30 resolving to the same fallback icon.
 */
export const WORKER_ICONS: LucideIcon[] = [
  Bot,
  Cat,
  Dog,
  Bird,
  Fish,
  Bug,
  Snail,
  Turtle,
  Squirrel,
  Cherry,
  Apple,
  Carrot,
  Leaf,
  Sprout,
  TreeDeciduous,
  Flower2,
  Mountain,
  Sun,
  Moon,
  Cloud,
  Snowflake,
  Sparkles,
  Star,
  Rocket,
  Plane,
  Anchor,
  Compass,
  Telescope,
  Atom,
  Crown, // (also in pool — only worker w/ crown is statistically rare; included to fill 30)
];

function hash(str: string): number {
  let h = 2166136261;
  for (let i = 0; i < str.length; i++) {
    h ^= str.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

export function getAgentIcon(input: {
  agentId?: string | null;
  isLead?: boolean | null;
  role?: string | null;
  agentName?: string | null;
}): LucideIcon {
  const role = input.role?.toLowerCase();
  const name = input.agentName?.toLowerCase();
  if (input.isLead || role === "lead" || name === "lead") return Crown;
  const seed = input.agentId ?? input.agentName ?? "";
  if (!seed) return Bot;
  return WORKER_ICONS[hash(seed) % 30] ?? Bot;
}

/**
 * Curated catalog for the avatar picker + custom-avatar renderer. Superset of
 * `WORKER_ICONS` (kept separate — that pool stays untouched so the
 * deterministic fallback for existing agents never shifts). Keys are the
 * kebab-case names stored in `AgentAvatar.icon`; adding an icon here is a
 * UI-only change (no migration, no server change — the server only validates
 * the kebab-case shape).
 */
export const AVATAR_ICON_CATALOG: Record<string, LucideIcon> = {
  bot: Bot,
  cat: Cat,
  dog: Dog,
  bird: Bird,
  fish: Fish,
  bug: Bug,
  snail: Snail,
  turtle: Turtle,
  squirrel: Squirrel,
  rabbit: Rabbit,
  cherry: Cherry,
  apple: Apple,
  carrot: Carrot,
  leaf: Leaf,
  sprout: Sprout,
  "tree-deciduous": TreeDeciduous,
  flower: Flower2,
  mountain: Mountain,
  sun: Sun,
  moon: Moon,
  cloud: Cloud,
  snowflake: Snowflake,
  sparkles: Sparkles,
  star: Star,
  rocket: Rocket,
  plane: Plane,
  anchor: Anchor,
  compass: Compass,
  telescope: Telescope,
  atom: Atom,
  crown: Crown,
  award: Award,
  book: Book,
  box: Box,
  briefcase: Briefcase,
  camera: Camera,
  coffee: Coffee,
  diamond: Diamond,
  droplet: Droplet,
  feather: Feather,
  flag: Flag,
  flame: Flame,
  gem: Gem,
  ghost: Ghost,
  gift: Gift,
  globe: Globe,
  heart: Heart,
  key: Key,
  lock: Lock,
  map: MapIcon,
  music: Music,
  package: Package,
  palette: Palette,
  pizza: Pizza,
  puzzle: Puzzle,
  shield: Shield,
  skull: Skull,
  sword: Sword,
  target: Target,
  trophy: Trophy,
  umbrella: Umbrella,
  wand: Wand2,
  zap: Zap,
  "a-arrow-down": AArrowDown,
  "a-arrow-up": AArrowUp,
  "a-large-small": ALargeSmall,
  accessibility: Accessibility,
  activity: Activity,
  "activity-square": ActivitySquare,
  "air-vent": AirVent,
  airplay: Airplay,
  "alarm-check": AlarmCheck,
  "alarm-clock": AlarmClock,
  "alarm-clock-check": AlarmClockCheck,
  "alarm-clock-minus": AlarmClockMinus,
  "alarm-clock-off": AlarmClockOff,
  "alarm-clock-plus": AlarmClockPlus,
  "alarm-minus": AlarmMinus,
  "alarm-plus": AlarmPlus,
  "alarm-smoke": AlarmSmoke,
  album: Album,
  "alert-circle": AlertCircle,
  "alert-octagon": AlertOctagon,
  "alert-triangle": AlertTriangle,
  "align-center": AlignCenter,
  "align-center-horizontal": AlignCenterHorizontal,
  "align-center-vertical": AlignCenterVertical,
  "align-end-horizontal": AlignEndHorizontal,
  "align-end-vertical": AlignEndVertical,
  "align-horizontal-distribute-center": AlignHorizontalDistributeCenter,
  "align-horizontal-distribute-end": AlignHorizontalDistributeEnd,
  "align-horizontal-distribute-start": AlignHorizontalDistributeStart,
  "align-horizontal-justify-center": AlignHorizontalJustifyCenter,
  "align-horizontal-justify-end": AlignHorizontalJustifyEnd,
  "align-horizontal-justify-start": AlignHorizontalJustifyStart,
  "align-horizontal-space-around": AlignHorizontalSpaceAround,
  "align-horizontal-space-between": AlignHorizontalSpaceBetween,
  "align-justify": AlignJustify,
  "align-left": AlignLeft,
  "align-right": AlignRight,
  "align-start-horizontal": AlignStartHorizontal,
  "align-start-vertical": AlignStartVertical,
  "align-vertical-distribute-center": AlignVerticalDistributeCenter,
  "align-vertical-distribute-end": AlignVerticalDistributeEnd,
  "align-vertical-distribute-start": AlignVerticalDistributeStart,
  "align-vertical-justify-center": AlignVerticalJustifyCenter,
  "align-vertical-justify-end": AlignVerticalJustifyEnd,
  "align-vertical-justify-start": AlignVerticalJustifyStart,
  "align-vertical-space-around": AlignVerticalSpaceAround,
  "align-vertical-space-between": AlignVerticalSpaceBetween,
  ambulance: Ambulance,
  ampersand: Ampersand,
  ampersands: Ampersands,
  amphora: Amphora,
  angry: Angry,
  annoyed: Annoyed,
  antenna: Antenna,
  anvil: Anvil,
  aperture: Aperture,
  "app-window": AppWindow,
  "app-window-mac": AppWindowMac,
  archive: Archive,
  "archive-restore": ArchiveRestore,
  "archive-x": ArchiveX,
  "area-chart": AreaChart,
  armchair: Armchair,
  "arrow-big-down": ArrowBigDown,
  "arrow-big-down-dash": ArrowBigDownDash,
  "arrow-big-left": ArrowBigLeft,
  "arrow-big-left-dash": ArrowBigLeftDash,
  "arrow-big-right": ArrowBigRight,
  "arrow-big-right-dash": ArrowBigRightDash,
  "arrow-big-up": ArrowBigUp,
  "arrow-big-up-dash": ArrowBigUpDash,
  "arrow-down": ArrowDown,
  "arrow-down-az": ArrowDownAz,
  "arrow-down-circle": ArrowDownCircle,
  "arrow-down-from-line": ArrowDownFromLine,
  "arrow-down-left": ArrowDownLeft,
  "arrow-down-left-from-circle": ArrowDownLeftFromCircle,
  "arrow-down-left-from-square": ArrowDownLeftFromSquare,
  "arrow-down-left-square": ArrowDownLeftSquare,
  "arrow-down-narrow-wide": ArrowDownNarrowWide,
  "arrow-down-right": ArrowDownRight,
  "arrow-down-right-from-circle": ArrowDownRightFromCircle,
  "arrow-down-right-from-square": ArrowDownRightFromSquare,
  "arrow-down-right-square": ArrowDownRightSquare,
  "arrow-down-square": ArrowDownSquare,
  "arrow-down-to-dot": ArrowDownToDot,
  "arrow-down-to-line": ArrowDownToLine,
  "arrow-down-up": ArrowDownUp,
  "arrow-down-wide-narrow": ArrowDownWideNarrow,
  "arrow-down-za": ArrowDownZa,
  "arrow-left": ArrowLeft,
  "arrow-left-circle": ArrowLeftCircle,
  "arrow-left-from-line": ArrowLeftFromLine,
  "arrow-left-right": ArrowLeftRight,
  "arrow-left-square": ArrowLeftSquare,
  "arrow-left-to-line": ArrowLeftToLine,
  "arrow-right": ArrowRight,
  "arrow-right-circle": ArrowRightCircle,
  "arrow-right-from-line": ArrowRightFromLine,
  "arrow-right-left": ArrowRightLeft,
  "arrow-right-square": ArrowRightSquare,
  "arrow-right-to-line": ArrowRightToLine,
  "arrow-up": ArrowUp,
  "arrow-up-az": ArrowUpAz,
  "arrow-up-circle": ArrowUpCircle,
  "arrow-up-down": ArrowUpDown,
  "arrow-up-from-dot": ArrowUpFromDot,
  "arrow-up-from-line": ArrowUpFromLine,
  "arrow-up-left": ArrowUpLeft,
  "arrow-up-left-from-circle": ArrowUpLeftFromCircle,
  "arrow-up-left-from-square": ArrowUpLeftFromSquare,
  "arrow-up-left-square": ArrowUpLeftSquare,
  "arrow-up-narrow-wide": ArrowUpNarrowWide,
  "arrow-up-right": ArrowUpRight,
  "arrow-up-right-from-circle": ArrowUpRightFromCircle,
  "arrow-up-right-from-square": ArrowUpRightFromSquare,
  "arrow-up-right-square": ArrowUpRightSquare,
  "arrow-up-square": ArrowUpSquare,
  "arrow-up-to-line": ArrowUpToLine,
  "arrow-up-wide-narrow": ArrowUpWideNarrow,
  "arrow-up-za": ArrowUpZa,
  "arrows-up-from-line": ArrowsUpFromLine,
  asterisk: Asterisk,
  "asterisk-square": AsteriskSquare,
  "at-sign": AtSign,
  "audio-lines": AudioLines,
  "audio-waveform": AudioWaveform,
  axe: Axe,
  baby: Baby,
  backpack: Backpack,
  badge: Badge,
  "badge-alert": BadgeAlert,
  "badge-cent": BadgeCent,
  "badge-check": BadgeCheck,
  "badge-dollar-sign": BadgeDollarSign,
  "badge-euro": BadgeEuro,
  "badge-help": BadgeHelp,
  "badge-indian-rupee": BadgeIndianRupee,
  "badge-info": BadgeInfo,
  "badge-japanese-yen": BadgeJapaneseYen,
  "badge-minus": BadgeMinus,
  "badge-percent": BadgePercent,
  "badge-plus": BadgePlus,
  "badge-pound-sterling": BadgePoundSterling,
  "badge-question-mark": BadgeQuestionMark,
  "badge-russian-ruble": BadgeRussianRuble,
  "badge-swiss-franc": BadgeSwissFranc,
  "badge-turkish-lira": BadgeTurkishLira,
  "badge-x": BadgeX,
  "baggage-claim": BaggageClaim,
  balloon: Balloon,
  ban: Ban,
  banana: Banana,
  bandage: Bandage,
  banknote: Banknote,
  "banknote-arrow-down": BanknoteArrowDown,
  "banknote-arrow-up": BanknoteArrowUp,
  "banknote-x": BanknoteX,
  "bar-chart": BarChart,
  "bar-chart-big": BarChartBig,
  "bar-chart-horizontal": BarChartHorizontal,
  "bar-chart-horizontal-big": BarChartHorizontalBig,
  barcode: Barcode,
  barrel: Barrel,
  baseline: Baseline,
  bath: Bath,
  battery: Battery,
  "battery-charging": BatteryCharging,
  "battery-full": BatteryFull,
  "battery-low": BatteryLow,
  "battery-medium": BatteryMedium,
  "battery-plus": BatteryPlus,
  "battery-warning": BatteryWarning,
  beaker: Beaker,
  bean: Bean,
  "bean-off": BeanOff,
  bed: Bed,
  "bed-double": BedDouble,
  "bed-single": BedSingle,
  beef: Beef,
  beer: Beer,
  "beer-off": BeerOff,
  bell: Bell,
  "bell-dot": BellDot,
  "bell-electric": BellElectric,
  "bell-minus": BellMinus,
  "bell-off": BellOff,
  "bell-plus": BellPlus,
  "bell-ring": BellRing,
  "between-horizonal-end": BetweenHorizonalEnd,
  "between-horizonal-start": BetweenHorizonalStart,
  "between-horizontal-end": BetweenHorizontalEnd,
  "between-horizontal-start": BetweenHorizontalStart,
  "between-vertical-end": BetweenVerticalEnd,
  "between-vertical-start": BetweenVerticalStart,
  "biceps-flexed": BicepsFlexed,
  bike: Bike,
  binary: Binary,
  binoculars: Binoculars,
  biohazard: Biohazard,
  birdhouse: Birdhouse,
  bitcoin: Bitcoin,
  blend: Blend,
  blinds: Blinds,
  blocks: Blocks,
  bluetooth: Bluetooth,
  "bluetooth-connected": BluetoothConnected,
  "bluetooth-off": BluetoothOff,
  "bluetooth-searching": BluetoothSearching,
  bold: Bold,
  bolt: Bolt,
  bomb: Bomb,
  bone: Bone,
  "book-a": BookA,
  "book-alert": BookAlert,
  "book-audio": BookAudio,
  "book-check": BookCheck,
  "book-copy": BookCopy,
  "book-dashed": BookDashed,
  "book-down": BookDown,
  "book-headphones": BookHeadphones,
  "book-heart": BookHeart,
  "book-image": BookImage,
  "book-key": BookKey,
  "book-lock": BookLock,
  "book-marked": BookMarked,
  "book-minus": BookMinus,
  "book-open": BookOpen,
  "book-open-check": BookOpenCheck,
  "book-open-text": BookOpenText,
  "book-plus": BookPlus,
  "book-search": BookSearch,
  "book-template": BookTemplate,
  "book-text": BookText,
  "book-type": BookType,
  "book-up": BookUp,
  "book-user": BookUser,
  "book-x": BookX,
  bookmark: Bookmark,
  "bookmark-check": BookmarkCheck,
  "bookmark-minus": BookmarkMinus,
  "bookmark-plus": BookmarkPlus,
  "bookmark-x": BookmarkX,
  "boom-box": BoomBox,
  "bot-message-square": BotMessageSquare,
  "bot-off": BotOff,
  "bottle-wine": BottleWine,
  "bow-arrow": BowArrow,
  "box-select": BoxSelect,
  boxes: Boxes,
  braces: Braces,
  brackets: Brackets,
  brain: Brain,
  "brain-circuit": BrainCircuit,
  "brain-cog": BrainCog,
  "brick-wall": BrickWall,
  "brick-wall-fire": BrickWallFire,
  "brick-wall-shield": BrickWallShield,
  "briefcase-business": BriefcaseBusiness,
  "briefcase-conveyor-belt": BriefcaseConveyorBelt,
  "briefcase-medical": BriefcaseMedical,
  "bring-to-front": BringToFront,
  brush: Brush,
  "brush-cleaning": BrushCleaning,
  bubbles: Bubbles,
  "bug-off": BugOff,
  "bug-play": BugPlay,
  building: Building,
  bus: Bus,
  "bus-front": BusFront,
  cable: Cable,
  "cable-car": CableCar,
  cake: Cake,
  "cake-slice": CakeSlice,
  calculator: Calculator,
  calendar: Calendar,
  "calendar-arrow-down": CalendarArrowDown,
  "calendar-arrow-up": CalendarArrowUp,
  "calendar-check": CalendarCheck,
  "calendar-clock": CalendarClock,
  "calendar-cog": CalendarCog,
  "calendar-days": CalendarDays,
  "calendar-fold": CalendarFold,
  "calendar-heart": CalendarHeart,
  "calendar-minus": CalendarMinus,
  "calendar-off": CalendarOff,
  "calendar-plus": CalendarPlus,
  "calendar-range": CalendarRange,
  "calendar-search": CalendarSearch,
  "calendar-sync": CalendarSync,
  "calendar-x": CalendarX,
  calendars: Calendars,
  "camera-off": CameraOff,
  "candlestick-chart": CandlestickChart,
  candy: Candy,
  "candy-cane": CandyCane,
  "candy-off": CandyOff,
  cannabis: Cannabis,
  "cannabis-off": CannabisOff,
  captions: Captions,
  "captions-off": CaptionsOff,
  car: Car,
  "car-front": CarFront,
  "car-taxi-front": CarTaxiFront,
  caravan: Caravan,
  "card-sim": CardSim,
  "case-lower": CaseLower,
  "case-sensitive": CaseSensitive,
  "case-upper": CaseUpper,
  "cassette-tape": CassetteTape,
  cast: Cast,
  castle: Castle,
  cctv: Cctv,
  "chart-area": ChartArea,
  "chart-bar": ChartBar,
  "chart-bar-big": ChartBarBig,
  "chart-bar-decreasing": ChartBarDecreasing,
  "chart-bar-increasing": ChartBarIncreasing,
  "chart-bar-stacked": ChartBarStacked,
  "chart-candlestick": ChartCandlestick,
  "chart-column": ChartColumn,
  "chart-column-big": ChartColumnBig,
  "chart-column-decreasing": ChartColumnDecreasing,
  "chart-column-increasing": ChartColumnIncreasing,
  "chart-column-stacked": ChartColumnStacked,
  "chart-gantt": ChartGantt,
  "chart-line": ChartLine,
  "chart-network": ChartNetwork,
  "chart-no-axes-column": ChartNoAxesColumn,
  "chart-no-axes-column-decreasing": ChartNoAxesColumnDecreasing,
  "chart-no-axes-column-increasing": ChartNoAxesColumnIncreasing,
  "chart-no-axes-combined": ChartNoAxesCombined,
};

/** The original familiar 64 choices shown until a search narrows the catalog. */
export const DEFAULT_AVATAR_ICON_NAMES = Object.keys(AVATAR_ICON_CATALOG).slice(0, 64);
export const MAX_AVATAR_ICON_SEARCH_RESULTS = 100;

/**
 * Filters the static picker catalog without coupling the search behavior to
 * the popover. Spaces and hyphens are intentionally equivalent so people can
 * discover names such as `tree-deciduous` by typing natural words.
 */
export function searchAvatarIcons(query: string): { iconResults: string[]; totalMatches: number } {
  const normalizedQuery = query.toLowerCase().replace(/[\s-]+/g, "");
  if (!normalizedQuery) {
    return {
      iconResults: DEFAULT_AVATAR_ICON_NAMES,
      totalMatches: DEFAULT_AVATAR_ICON_NAMES.length,
    };
  }

  const matches = Object.keys(AVATAR_ICON_CATALOG).filter((icon) =>
    icon
      .toLowerCase()
      .replace(/[\s-]+/g, "")
      .includes(normalizedQuery),
  );
  return {
    iconResults: matches.slice(0, MAX_AVATAR_ICON_SEARCH_RESULTS),
    totalMatches: matches.length,
  };
}

/** Resolves an agent's rendered icon: stored catalog icon wins; unset/unknown
 * falls back to the existing deterministic derivation, so a stale or
 * hand-set icon name can never break rendering. */
export function resolveAgentIcon(
  avatar: AgentAvatar | null | undefined,
  fallbackInputs: {
    agentId?: string | null;
    isLead?: boolean | null;
    role?: string | null;
    agentName?: string | null;
  },
): LucideIcon {
  if (avatar?.type === "lucide") {
    const catalogIcon = AVATAR_ICON_CATALOG[avatar.icon];
    if (catalogIcon) return catalogIcon;
  }
  return getAgentIcon(fallbackInputs);
}
