/**
 * Deterministic icon picker for agent avatars. Lead always gets a crown so
 * the coordinator visually pops. Workers get one of 30 distinct lucide
 * icons seeded by agent id (NOT name — names can change, ids don't).
 */

import {
  Anchor,
  Apple,
  Atom,
  Award,
  Bird,
  Book,
  Bot,
  Box,
  Briefcase,
  Bug,
  Camera,
  Carrot,
  Cat,
  Cherry,
  Cloud,
  Coffee,
  Compass,
  Crown,
  Diamond,
  Dog,
  Droplet,
  Feather,
  Fish,
  Flag,
  Flame,
  Flower2,
  Gem,
  Ghost,
  Gift,
  Globe,
  Heart,
  Key,
  Leaf,
  Lock,
  type LucideIcon,
  type LucideProps,
  Map as MapIcon,
  Moon,
  Mountain,
  Music,
  Package,
  Palette,
  Pizza,
  Plane,
  Puzzle,
  Rabbit,
  Rocket,
  Shield,
  Skull,
  Snail,
  Snowflake,
  Sparkles,
  Sprout,
  Squirrel,
  Star,
  Sun,
  Sword,
  Target,
  Telescope,
  TreeDeciduous,
  Trophy,
  Turtle,
  Umbrella,
  Wand2,
  Zap,
} from "lucide-react";
import type { DynamicIcon } from "lucide-react/dynamic";
import { createElement, forwardRef, useEffect, useState } from "react";
import type { AgentAvatar } from "@/api/types";
import { LUCIDE_ICON_NAMES } from "./lucide-icon-names.generated";

const WORKER_ICONS: LucideIcon[] = [
  Bot,
  Cat,
  Dog,
  Bird,
  Fish,
  Bug,
  Snail,
  Turtle,
  Squirrel,
  Cherry,
  Apple,
  Carrot,
  Leaf,
  Sprout,
  TreeDeciduous,
  Flower2,
  Mountain,
  Sun,
  Moon,
  Cloud,
  Snowflake,
  Sparkles,
  Star,
  Rocket,
  Plane,
  Anchor,
  Compass,
  Telescope,
  Atom,
  Crown, // (also in pool — only worker w/ crown is statistically rare; included to fill 30)
];

function hash(str: string): number {
  let h = 2166136261;
  for (let i = 0; i < str.length; i++) {
    h ^= str.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

export function getAgentIcon(input: {
  agentId?: string | null;
  isLead?: boolean | null;
  role?: string | null;
  agentName?: string | null;
}): LucideIcon {
  const role = input.role?.toLowerCase();
  const name = input.agentName?.toLowerCase();
  if (input.isLead || role === "lead" || name === "lead") return Crown;
  const seed = input.agentId ?? input.agentName ?? "";
  if (!seed) return Bot;
  return WORKER_ICONS[hash(seed) % WORKER_ICONS.length] ?? Bot;
}

/**
 * Curated catalog for the avatar picker + custom-avatar renderer. Superset of
 * `WORKER_ICONS` (kept separate — that pool stays untouched so the
 * deterministic fallback for existing agents never shifts). Keys are the
 * kebab-case names stored in `AgentAvatar.icon`; adding an icon here is a
 * UI-only change (no migration, no server change — the server only validates
 * the kebab-case shape).
 */
export const AVATAR_ICON_CATALOG: Record<string, LucideIcon> = {
  bot: Bot,
  cat: Cat,
  dog: Dog,
  bird: Bird,
  fish: Fish,
  bug: Bug,
  snail: Snail,
  turtle: Turtle,
  squirrel: Squirrel,
  rabbit: Rabbit,
  cherry: Cherry,
  apple: Apple,
  carrot: Carrot,
  leaf: Leaf,
  sprout: Sprout,
  "tree-deciduous": TreeDeciduous,
  flower: Flower2,
  mountain: Mountain,
  sun: Sun,
  moon: Moon,
  cloud: Cloud,
  snowflake: Snowflake,
  sparkles: Sparkles,
  star: Star,
  rocket: Rocket,
  plane: Plane,
  anchor: Anchor,
  compass: Compass,
  telescope: Telescope,
  atom: Atom,
  crown: Crown,
  award: Award,
  book: Book,
  box: Box,
  briefcase: Briefcase,
  camera: Camera,
  coffee: Coffee,
  diamond: Diamond,
  droplet: Droplet,
  feather: Feather,
  flag: Flag,
  flame: Flame,
  gem: Gem,
  ghost: Ghost,
  gift: Gift,
  globe: Globe,
  heart: Heart,
  key: Key,
  lock: Lock,
  map: MapIcon,
  music: Music,
  package: Package,
  palette: Palette,
  pizza: Pizza,
  puzzle: Puzzle,
  shield: Shield,
  skull: Skull,
  sword: Sword,
  target: Target,
  trophy: Trophy,
  umbrella: Umbrella,
  wand: Wand2,
  zap: Zap,
};

/**
 * The full searchable icon surface: every kebab-case name resolvable via
 * `lucide-react/dynamic`'s `DynamicIcon` for the pinned `lucide-react`
 * version, deduped so deprecated aliases (e.g. `alarm-check` for
 * `alarm-clock-check`) don't show up as visually-identical duplicate search
 * results. Generated by `apps/ui/scripts/refresh-lucide-icon-names.ts` — see
 * that file to regenerate after a `lucide-react` bump.
 */
const LUCIDE_ICON_NAME_SET: ReadonlySet<string> = new Set(LUCIDE_ICON_NAMES);

/** Shown when the picker's search box is empty — the same 64 icons that made
 * up the catalog before full-library search existed. Kept as an explicit
 * list derived from `AVATAR_ICON_CATALOG` (not a slice of the full library),
 * so the default shortlist can never silently drift as the library grows. */
export const DEFAULT_AVATAR_ICON_NAMES: readonly string[] = Object.keys(AVATAR_ICON_CATALOG);

export const MAX_AVATAR_ICON_SEARCH_RESULTS = 100;

/** Per-name cache of lazily-rendered icon components, so the wrapper's
 * identity stays stable across renders — a fresh function on every call
 * would remount (and re-fetch) the icon on every parent re-render. */
const dynamicIconComponentCache = new Map<string, LucideIcon>();

/** Renders an icon from the full lucide library via a chunk this component
 * only requests once mounted. `lucide-react/dynamic`'s ~1,900-entry loader
 * map is sizable (see apps/ui/CLAUDE.md avatar-icon notes), so it's reached
 * through a dynamic `import()` here rather than a static import at module
 * scope — that would put the full map in every bundle that renders an
 * agent's avatar, not just the rare one whose stored icon falls outside
 * `AVATAR_ICON_CATALOG`. */
function getDynamicIconComponent(name: string): LucideIcon {
  const cached = dynamicIconComponentCache.get(name);
  if (cached) return cached;
  const Component = forwardRef<SVGSVGElement, LucideProps>((props, ref) => {
    const [DynamicIconComponent, setDynamicIconComponent] = useState<typeof DynamicIcon | null>(
      null,
    );
    useEffect(() => {
      let cancelled = false;
      import("./lucide-dynamic-icon").then((mod) => {
        if (!cancelled) setDynamicIconComponent(() => mod.DynamicIcon);
      });
      return () => {
        cancelled = true;
      };
    }, []);
    if (!DynamicIconComponent) return null;
    // biome-ignore lint/suspicious/noExplicitAny: `name` is runtime-validated against LUCIDE_ICON_NAME_SET, not lucide's generated name union
    const dynamicIconName = name as any;
    return createElement(DynamicIconComponent, { name: dynamicIconName, ref, ...props });
  });
  Component.displayName = `DynamicAvatarIcon(${name})`;
  // Cast: structurally identical to LucideIcon (forwardRef over SVG props) but built at
  // runtime, so it can't share the exact generic instantiation lucide-react's icons use.
  dynamicIconComponentCache.set(name, Component as unknown as LucideIcon);
  return Component as unknown as LucideIcon;
}

/** Resolves any valid kebab-case icon name to a renderable component: the
 * small eager catalog first (sync, no loading flash), then the full
 * lucide-react library lazily. Returns `undefined` for names that aren't a
 * real icon, so callers can fall back safely instead of rendering nothing. */
export function getIconComponentByName(name: string): LucideIcon | undefined {
  const catalogIcon = AVATAR_ICON_CATALOG[name];
  if (catalogIcon) return catalogIcon;
  if (LUCIDE_ICON_NAME_SET.has(name)) return getDynamicIconComponent(name);
  return undefined;
}

function normalizeIconQuery(value: string): string {
  return value.toLowerCase().replace(/[\s-]+/g, "");
}

export interface AvatarIconSearchResult {
  /** Up to `MAX_AVATAR_ICON_SEARCH_RESULTS` matching icon names. */
  names: readonly string[];
  /** True count of matches, even when `names` was capped — lets the picker
   * show an honest "showing N of totalMatches" affordance. */
  totalMatches: number;
}

/** Searches the full lucide icon library (space/hyphen-insensitive). An
 * empty query returns the curated `DEFAULT_AVATAR_ICON_NAMES` shortlist. */
export function searchAvatarIcons(query: string): AvatarIconSearchResult {
  const normalizedQuery = normalizeIconQuery(query);
  if (!normalizedQuery) {
    return { names: DEFAULT_AVATAR_ICON_NAMES, totalMatches: DEFAULT_AVATAR_ICON_NAMES.length };
  }
  const matches = LUCIDE_ICON_NAMES.filter((name) =>
    normalizeIconQuery(name).includes(normalizedQuery),
  );
  return {
    names: matches.slice(0, MAX_AVATAR_ICON_SEARCH_RESULTS),
    totalMatches: matches.length,
  };
}

/** Resolves an agent's rendered icon: stored catalog icon wins; unset/unknown
 * falls back to the existing deterministic derivation, so a stale or
 * hand-set icon name can never break rendering. */
export function resolveAgentIcon(
  avatar: AgentAvatar | null | undefined,
  fallbackInputs: {
    agentId?: string | null;
    isLead?: boolean | null;
    role?: string | null;
    agentName?: string | null;
  },
): LucideIcon {
  if (avatar?.type === "lucide") {
    const icon = getIconComponentByName(avatar.icon);
    if (icon) return icon;
  }
  return getAgentIcon(fallbackInputs);
}
